In [27]:
import pandas as pd
import pathlib
from pathlib import Path

In [28]:
cwd = Path.cwd()  # current working directory

print(cwd)


raw_data_dir = cwd.joinpath("swiss-bank-risk-project", "data")
print(raw_data_dir)

raw_data_folder = raw_data_dir.joinpath("raw")

processed_data_folder = raw_data_dir.joinpath("processed")
processed_data_folder.mkdir(parents=True, exist_ok=True)


print(raw_data_folder)
print(processed_data_folder)

/files
/files/swiss-bank-risk-project/data
/files/swiss-bank-risk-project/data/raw
/files/swiss-bank-risk-project/data/processed

In [29]:
csv_files = []

for file in raw_data_folder.glob("*.csv"):
    csv_files.append(file)

datasets = {}

for file in csv_files:
    datasets[file.stem] = pd.read_csv(file)

print(len(csv_files))
print(datasets.keys())

4
dict_keys(['ciss_index', 'snb_interest_policy_rates_control', 'chf-eur_exchange_rate_control', 'swiss_banks_and_goverment_bond_yields'])

In [30]:
for name, df in datasets.items():
    print(name)
    print(df.shape)
    print(df.columns)
    print(df.dtypes)
    display(df.head())

ciss_index
(4073, 40)
Index(['KEY', 'FREQ', 'REF_AREA', 'CURRENCY', 'PROVIDER_FM', 'INSTRUMENT_FM',
       'PROVIDER_FM_ID', 'DATA_TYPE_FM', 'TIME_PERIOD', 'OBS_VALUE',
       'OBS_STATUS', 'OBS_CONF', 'OBS_PRE_BREAK', 'OBS_COM', 'TIME_FORMAT',
       'BREAKS', 'COLLECTION', 'COMPILING_ORG', 'DISS_ORG', 'DOM_SER_IDS',
       'FM_CONTRACT_TIME', 'FM_COUPON_RATE', 'FM_IDENTIFIER', 'FM_LOT_SIZE',
       'FM_MATURITY', 'FM_OUTS_AMOUNT', 'FM_PUT_CALL', 'FM_STRIKE_PRICE',
       'PUBL_MU', 'PUBL_PUBLIC', 'UNIT_INDEX_BASE', 'COMPILATION', 'COVERAGE',
       'DECIMALS', 'SOURCE_AGENCY', 'SOURCE_PUB', 'TITLE', 'TITLE_COMPL',
       'UNIT', 'UNIT_MULT'],
      dtype='object')
KEY                  object
FREQ                 object
REF_AREA             object
CURRENCY             object
PROVIDER_FM          object
INSTRUMENT_FM        object
PROVIDER_FM_ID       object
DATA_TYPE_FM         object
TIME_PERIOD          object
OBS_VALUE           float64
OBS_STATUS           object
OBS_CONF             object
OBS_PRE_BREAK       float64
OBS_COM             float64
TIME_FORMAT          object
BREAKS              float64
COLLECTION           object
COMPILING_ORG       float64
DISS_ORG            float64
DOM_SER_IDS         float64
FM_CONTRACT_TIME    float64
FM_COUPON_RATE      float64
FM_IDENTIFIER       float64
FM_LOT_SIZE         float64
FM_MATURITY         float64
FM_OUTS_AMOUNT      float64
FM_PUT_CALL         float64
FM_STRIKE_PRICE     float64
PUBL_MU             float64
PUBL_PUBLIC         float64
UNIT_INDEX_BASE     float64
COMPILATION         float64
COVERAGE            float64
DECIMALS              int64
SOURCE_AGENCY        object
SOURCE_PUB          float64
TITLE                object
TITLE_COMPL          object
UNIT                 object
UNIT_MULT             int64
dtype: object

,KEY,FREQ,REF_AREA,CURRENCY,PROVIDER_FM,INSTRUMENT_FM,PROVIDER_FM_ID,DATA_TYPE_FM,TIME_PERIOD,OBS_VALUE,...,UNIT_INDEX_BASE,COMPILATION,COVERAGE,DECIMALS,SOURCE_AGENCY,SOURCE_PUB,TITLE,TITLE_COMPL,UNIT,UNIT_MULT
0,CISS.D.U2.Z0Z.4F.EC.SS_CIN.IDX,D,U2,Z0Z,4F,EC,SS_CIN,IDX,2010-01-01,0.164916,...,NaN,NaN,NaN,4,4F0,NaN,NEW CISS - Composite Indicator of Systemic Str...,"Euro area (changing composition), New Composit...",PURE_NUMB,0
1,CISS.D.U2.Z0Z.4F.EC.SS_CIN.IDX,D,U2,Z0Z,4F,EC,SS_CIN,IDX,2010-01-04,0.175476,...,NaN,NaN,NaN,4,4F0,NaN,NEW CISS - Composite Indicator of Systemic Str...,"Euro area (changing composition), New Composit...",PURE_NUMB,0
2,CISS.D.U2.Z0Z.4F.EC.SS_CIN.IDX,D,U2,Z0Z,4F,EC,SS_CIN,IDX,2010-01-05,0.173165,...,NaN,NaN,NaN,4,4F0,NaN,NEW CISS - Composite Indicator of Systemic Str...,"Euro area (changing composition), New Composit...",PURE_NUMB,0
3,CISS.D.U2.Z0Z.4F.EC.SS_CIN.IDX,D,U2,Z0Z,4F,EC,SS_CIN,IDX,2010-01-06,0.167020,...,NaN,NaN,NaN,4,4F0,NaN,NEW CISS - Composite Indicator of Systemic Str...,"Euro area (changing composition), New Composit...",PURE_NUMB,0
4,CISS.D.U2.Z0Z.4F.EC.SS_CIN.IDX,D,U2,Z0Z,4F,EC,SS_CIN,IDX,2010-01-07,0.160805,...,NaN,NaN,NaN,4,4F0,NaN,NEW CISS - Composite Indicator of Systemic Str...,"Euro area (changing composition), New Composit...",PURE_NUMB,0

snb_interest_policy_rates_control
(563, 1)
Index(['CubeId;"snboffzisa"'], dtype='object')
CubeId;"snboffzisa"    object
dtype: object

                 CubeId;"snboffzisa"
0  PublishingDate;"2026-09-21 09:00"
1                  Date;"D0";"Value"
2                      2010-01;"LZ";
3                  2010-01;"UG0";"0"
4               2010-01;"OG0";"0.75"

chf-eur_exchange_rate_control
(3999, 32)
Index(['KEY', 'FREQ', 'CURRENCY', 'CURRENCY_DENOM', 'EXR_TYPE', 'EXR_SUFFIX',
       'TIME_PERIOD', 'OBS_VALUE', 'OBS_STATUS', 'OBS_CONF', 'OBS_PRE_BREAK',
       'OBS_COM', 'TIME_FORMAT', 'BREAKS', 'COLLECTION', 'COMPILING_ORG',
       'DISS_ORG', 'DOM_SER_IDS', 'PUBL_ECB', 'PUBL_MU', 'PUBL_PUBLIC',
       'UNIT_INDEX_BASE', 'COMPILATION', 'COVERAGE', 'DECIMALS', 'NAT_TITLE',
       'SOURCE_AGENCY', 'SOURCE_PUB', 'TITLE', 'TITLE_COMPL', 'UNIT',
       'UNIT_MULT'],
      dtype='object')
KEY                 object
FREQ                object
CURRENCY            object
CURRENCY_DENOM      object
EXR_TYPE            object
EXR_SUFFIX          object
TIME_PERIOD         object
OBS_VALUE          float64
OBS_STATUS          object
OBS_CONF            object
OBS_PRE_BREAK      float64
OBS_COM            float64
TIME_FORMAT         object
BREAKS             float64
COLLECTION          object
COMPILING_ORG      float64
DISS_ORG           float64
DOM_SER_IDS        float64
PUBL_ECB           float64
PUBL_MU            float64
PUBL_PUBLIC        float64
UNIT_INDEX_BASE     object
COMPILATION        float64
COVERAGE           float64
DECIMALS             int64
NAT_TITLE          float64
SOURCE_AGENCY       object
SOURCE_PUB         float64
TITLE               object
TITLE_COMPL         object
UNIT                object
UNIT_MULT            int64
dtype: object

,KEY,FREQ,CURRENCY,CURRENCY_DENOM,EXR_TYPE,EXR_SUFFIX,TIME_PERIOD,OBS_VALUE,OBS_STATUS,OBS_CONF,...,COMPILATION,COVERAGE,DECIMALS,NAT_TITLE,SOURCE_AGENCY,SOURCE_PUB,TITLE,TITLE_COMPL,UNIT,UNIT_MULT
0,EXR.D.CHF.EUR.SP00.A,D,CHF,EUR,SP00,A,2010-01-01,NaN,H,NaN,...,NaN,NaN,4,NaN,4F0,NaN,Swiss franc/Euro ECB reference exchange rate,"ECB reference exchange rate, Swiss franc/Euro,...",CHF,0
1,EXR.D.CHF.EUR.SP00.A,D,CHF,EUR,SP00,A,2010-01-04,1.4873,A,NaN,...,NaN,NaN,4,NaN,4F0,NaN,Swiss franc/Euro ECB reference exchange rate,"ECB reference exchange rate, Swiss franc/Euro,...",CHF,0
2,EXR.D.CHF.EUR.SP00.A,D,CHF,EUR,SP00,A,2010-01-05,1.4856,A,NaN,...,NaN,NaN,4,NaN,4F0,NaN,Swiss franc/Euro ECB reference exchange rate,"ECB reference exchange rate, Swiss franc/Euro,...",CHF,0
3,EXR.D.CHF.EUR.SP00.A,D,CHF,EUR,SP00,A,2010-01-06,1.4823,A,NaN,...,NaN,NaN,4,NaN,4F0,NaN,Swiss franc/Euro ECB reference exchange rate,"ECB reference exchange rate, Swiss franc/Euro,...",CHF,0
4,EXR.D.CHF.EUR.SP00.A,D,CHF,EUR,SP00,A,2010-01-07,1.4832,A,NaN,...,NaN,NaN,4,NaN,4F0,NaN,Swiss franc/Euro ECB reference exchange rate,"ECB reference exchange rate, Swiss franc/Euro,...",CHF,0

swiss_banks_and_goverment_bond_yields
(28457, 1)
Index(['CubeId;"rendoblid"'], dtype='object')
CubeId;"rendoblid"    object
dtype: object

                  CubeId;"rendoblid"
0  PublishingDate;"2025-09-01 14:29"
1                  Date;"D0";"Value"
2                   2010-01-01;"2J";
3                 2010-01-01;"10J0";
4                    2010-01-01;"E";

Explain why the cells should be standardized before merging

In [34]:
cleaned_datasets = {}

# CISS dataset

ciss = datasets["ciss_index"][["TIME_PERIOD", "OBS_VALUE"]].copy()

ciss = ciss.rename(columns={
    "TIME_PERIOD": "date",
    "OBS_VALUE": "value"
})

cleaned_datasets["ciss_index"] = ciss

print("ciss_index")
print(ciss.shape)
display(ciss.head())


# CHF/EUR exchange rate

exchange_rate = datasets["chf-eur_exchange_rate_control"][
    ["TIME_PERIOD", "OBS_VALUE"]
].copy()

exchange_rate = exchange_rate.rename(columns={
    "TIME_PERIOD": "date",
    "OBS_VALUE": "value"
})

cleaned_datasets["chf-eur_exchange_rate_control"] = exchange_rate

print("chf-eur_exchange_rate_control")
print(exchange_rate.shape)
display(exchange_rate.head())


# Find the SNB files

file_search = {file.stem: file for file in csv_files}

snb_rates = pd.read_csv(
    file_search["snb_interest_policy_rates_control"],
    sep=";",
    skiprows=2
)

bond_yields = pd.read_csv(
    file_search["swiss_banks_and_goverment_bond_yields"],
    sep=";",
    skiprows=2
)


# SNB policy rates

policy_rates = snb_rates.pivot(
    index="Date",
    columns="D0",
    values="Value"
).reset_index()

policy_rates["value"] = policy_rates["LZ"].combine_first(
    (policy_rates["UG0"] + policy_rates["OG0"]) / 2
)

policy_rates = policy_rates[["Date", "value"]].copy()

policy_rates = policy_rates.rename(columns={
    "Date": "date"
})

cleaned_datasets["snb_interest_policy_rates_control"] = policy_rates

print("snb_interest_policy_rates_control")
print(policy_rates.shape)
display(policy_rates.head())


# 10 year government bond yield

government_bond = bond_yields[
    bond_yields["D0"] == "10J0"
][["Date", "Value"]].copy()

government_bond = government_bond.rename(columns={
    "Date": "date",
    "Value": "value"
})

cleaned_datasets["swiss_banks_and_goverment_bond_yields"] = government_bond

print("swiss_banks_and_government_bond_yields")
print(government_bond.shape)
display(government_bond.head())


# Check that all four datasets are there

print(cleaned_datasets.keys())
print(len(cleaned_datasets))

ciss_index
(4073, 2)

         date     value
0  2010-01-01  0.164916
1  2010-01-04  0.175476
2  2010-01-05  0.173165
3  2010-01-06  0.167020
4  2010-01-07  0.160805

chf-eur_exchange_rate_control
(3999, 2)

         date   value
0  2010-01-01     NaN
1  2010-01-04  1.4873
2  2010-01-05  1.4856
3  2010-01-06  1.4823
4  2010-01-07  1.4832

snb_interest_policy_rates_control
(187, 2)

D0     date  value
0   2010-01  0.375
1   2010-02  0.375
2   2010-03  0.375
3   2010-04  0.375
4   2010-05  0.375

swiss_banks_and_government_bond_yields
(4065, 2)

          date  value
1   2010-01-01    NaN
8   2010-01-04  2.049
15  2010-01-05  2.065
22  2010-01-06  2.062
29  2010-01-07  2.070

dict_keys(['ciss_index', 'chf-eur_exchange_rate_control', 'snb_interest_policy_rates_control', 'swiss_banks_and_goverment_bond_yields'])
4

In [35]:
for name, dataframe in cleaned_datasets.items():
    time = cleaned_datasets[name]["date"]
    pd_date = pd.to_datetime(time, errors="coerce")
    dataframe["date"] = pd_date
    dataframe.sort_values("date", inplace=True)
    print(name)
    print(dataframe["date"].dtype)
    display(dataframe.head())
    
print(dataframe.isna().sum())

ciss_index
datetime64[ns]

        date     value
0 2010-01-01  0.164916
1 2010-01-04  0.175476
2 2010-01-05  0.173165
3 2010-01-06  0.167020
4 2010-01-07  0.160805

chf-eur_exchange_rate_control
datetime64[ns]

        date   value
0 2010-01-01     NaN
1 2010-01-04  1.4873
2 2010-01-05  1.4856
3 2010-01-06  1.4823
4 2010-01-07  1.4832

snb_interest_policy_rates_control
datetime64[ns]

D0       date  value
0  2010-01-01  0.375
1  2010-02-01  0.375
2  2010-03-01  0.375
3  2010-04-01  0.375
4  2010-05-01  0.375

swiss_banks_and_goverment_bond_yields
datetime64[ns]

         date  value
1  2010-01-01    NaN
8  2010-01-04  2.049
15 2010-01-05  2.065
22 2010-01-06  2.062
29 2010-01-07  2.070

date       0
value    149
dtype: int64

In [36]:
for name, dataframe in cleaned_datasets.items():
    pd_numeric_value = pd.to_numeric(dataframe["value"], errors="coerce")
    dataframe["value"] = pd_numeric_value
    print(name)
    print(dataframe["value"].dtype)
    display(dataframe.head())


print(dataframe.isna().sum())

ciss_index
float64

        date     value
0 2010-01-01  0.164916
1 2010-01-04  0.175476
2 2010-01-05  0.173165
3 2010-01-06  0.167020
4 2010-01-07  0.160805

chf-eur_exchange_rate_control
float64

        date   value
0 2010-01-01     NaN
1 2010-01-04  1.4873
2 2010-01-05  1.4856
3 2010-01-06  1.4823
4 2010-01-07  1.4832

snb_interest_policy_rates_control
float64

D0       date  value
0  2010-01-01  0.375
1  2010-02-01  0.375
2  2010-03-01  0.375
3  2010-04-01  0.375
4  2010-05-01  0.375

swiss_banks_and_goverment_bond_yields
float64

         date  value
1  2010-01-01    NaN
8  2010-01-04  2.049
15 2010-01-05  2.065
22 2010-01-06  2.062
29 2010-01-07  2.070

date       0
value    149
dtype: int64

In [37]:
for name, dataframe in cleaned_datasets.items():
    print(name)
    print(dataframe.isna().sum())
    print(dataframe.isna().mean() * 100)

ciss_index
date     0
value    0
dtype: int64
date     0.0
value    0.0
dtype: float64
chf-eur_exchange_rate_control
date     0
value    9
dtype: int64
date     0.000000
value    0.225056
dtype: float64
snb_interest_policy_rates_control
D0
date     0
value    0
dtype: int64
D0
date     0.0
value    0.0
dtype: float64
swiss_banks_and_goverment_bond_yields
date       0
value    149
dtype: int64
date     0.000000
value    3.665437
dtype: float64

In [38]:
for name, dataframe in cleaned_datasets.items():
    print(name)
    if dataframe["date"].duplicated().any() :
        print("There are duplicates")
    print(dataframe["date"].duplicated().sum())

ciss_index
0
chf-eur_exchange_rate_control
0
snb_interest_policy_rates_control
0
swiss_banks_and_goverment_bond_yields
0

We explain why we are converting all 4 weekly datasets before merging them together

In [57]:
weekly_datasets = {}

weekly_ciss = cleaned_datasets["ciss_index"].resample("W-FRI", on="date")["value"].mean().reset_index()

weekly_chf_eur_exchange_rate_control = cleaned_datasets["chf-eur_exchange_rate_control"].resample("W-FRI", on="date")["value"].mean().reset_index()

weekly_government_bond_yield = cleaned_datasets["swiss_banks_and_goverment_bond_yields"].resample("W-FRI", on="date")["value"].mean().reset_index()

weekly_policy_rate = cleaned_datasets["snb_interest_policy_rates_control"].set_index("date").resample("W-FRI").ffill().reset_index() 
# .ffill NA/NaN values by propagating the last valid observation to next valid.
# We do this because we have monthly values, given the policy rates change monthly and not daily.
# We therefore need to keep for each week until a new policy rate changes

weekly_datasets = {"ciss_index": weekly_ciss, "chf-eur_exchange_rate_control": weekly_chf_eur_exchange_rate_control, 
                   "swiss_banks_and_goverment_bond_yields": weekly_government_bond_yield, "snb_interest_policy_rates_control": weekly_policy_rate}

for name, weekly_df in weekly_datasets.items():
    print(name)
    print(weekly_df.shape)
    display(weekly_df.head())

ciss_index
(814, 2)

        date     value
0 2010-01-01  0.164916
1 2010-01-08  0.165886
2 2010-01-15  0.145988
3 2010-01-22  0.186101
4 2010-01-29  0.245768

chf-eur_exchange_rate_control
(814, 2)

        date    value
0 2010-01-01      NaN
1 2010-01-08  1.48398
2 2010-01-15  1.47692
3 2010-01-22  1.47398
4 2010-01-29  1.47118

swiss_banks_and_goverment_bond_yields
(814, 2)

        date   value
0 2010-01-01     NaN
1 2010-01-08  2.0620
2 2010-01-15  2.0262
3 2010-01-22  1.9894
4 2010-01-29  2.0164

snb_interest_policy_rates_control
(810, 2)

D0       date  value
0  2010-01-01  0.375
1  2010-01-08  0.375
2  2010-01-15  0.375
3  2010-01-22  0.375
4  2010-01-29  0.375

In [68]:
weekly_ciss.rename(columns={"value": "ciss_index"}, inplace=True)
display(weekly_datasets["ciss_index"].head())

weekly_chf_eur_exchange_rate_control.rename(columns={"value": "chf-eur_exchange_rate_control"}, inplace=True)
display(weekly_datasets["chf-eur_exchange_rate_control"].head())

        date  ciss_index
0 2010-01-01    0.164916
1 2010-01-08    0.165886
2 2010-01-15    0.145988
3 2010-01-22    0.186101
4 2010-01-29    0.245768

        date  chf_eur_exchange_rate
0 2010-01-01                    NaN
1 2010-01-08                1.48398
2 2010-01-15                1.47692
3 2010-01-22                1.47398
4 2010-01-29                1.47118

In [72]:
weekly_ciss.rename(columns={"value": "ciss_index"}, inplace=True)
display(weekly_datasets["ciss_index"].head())

weekly_chf_eur_exchange_rate_control.rename(columns={"value": "chf-eur_exchange_rate_control"}, inplace=True)
display(weekly_datasets["chf-eur_exchange_rate_control"].head())

weekly_government_bond_yield.rename(columns={"value": "government_bond_yield"}, inplace=True)
display(weekly_datasets["swiss_banks_and_goverment_bond_yields"].head())

weekly_policy_rate.rename(columns={"value": "snb_policy_rate"}, inplace=True)
display(weekly_datasets["snb_interest_policy_rates_control"].head())

        date  ciss_index
0 2010-01-01    0.164916
1 2010-01-08    0.165886
2 2010-01-15    0.145988
3 2010-01-22    0.186101
4 2010-01-29    0.245768

        date  chf_eur_exchange_rate
0 2010-01-01                    NaN
1 2010-01-08                1.48398
2 2010-01-15                1.47692
3 2010-01-22                1.47398
4 2010-01-29                1.47118

        date  government_bond_yield
0 2010-01-01                    NaN
1 2010-01-08                 2.0620
2 2010-01-15                 2.0262
3 2010-01-22                 1.9894
4 2010-01-29                 2.0164

D0       date  snb_policy_rate
0  2010-01-01            0.375
1  2010-01-08            0.375
2  2010-01-15            0.375
3  2010-01-22            0.375
4  2010-01-29            0.375

Just explain what you are about to do before writing the merge code

The datasets will be merged on the weekly date so that all indicators can be analysed together.

In [76]:
clean_weekly_datasets =  weekly_ciss.merge(
    weekly_chf_eur_exchange_rate_control,
    on="date",
    how="outer"
)

display(clean_weekly_datasets)

          date  ciss_index  chf_eur_exchange_rate
0   2010-01-01    0.164916                    NaN
1   2010-01-08    0.165886               1.483980
2   2010-01-15    0.145988               1.476920
3   2010-01-22    0.186101               1.473980
4   2010-01-29    0.245768               1.471180
..         ...         ...                    ...
809 2025-07-04    0.030363               0.933960
810 2025-07-11    0.028096               0.933200
811 2025-07-18    0.030874               0.931580
812 2025-07-25    0.032790               0.932820
813 2025-08-01    0.025498               0.930925

[814 rows x 3 columns]